# Generated by Django 2.2.24 on 2021-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210712_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Data_de_nascimento',
            field=models.DateField(max_length=8),
        ),
    ]
