# Generated by Django 2.2.24 on 2021-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20210726_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Data_de_nascimento',
            field=models.DateField(),
        ),
    ]
